cmake_minimum_required(VERSION 3.22.1)
project(smd_mp3 LANGUAGES C CXX)
set(CMAKE_C_STANDARD 99)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(LAME_DIR ${CMAKE_CURRENT_SOURCE_DIR}/third_party/lame)
set(LAME_SOURCES VbrTag bitstream encoder fft gain_analysis id3tag lame newmdct presets psymodel quantize quantize_pvt reservoir set_get tables takehiro util vbrquantize version mpglib_interface)
list(TRANSFORM LAME_SOURCES PREPEND "${LAME_DIR}/libmp3lame/")
list(TRANSFORM LAME_SOURCES APPEND ".c")
# Separate shared library permits replacement/relinking of LGPL library code.
add_library(mp3lame SHARED ${LAME_SOURCES})
target_include_directories(mp3lame PUBLIC ${LAME_DIR}/include PRIVATE ${LAME_DIR}/libmp3lame ${CMAKE_CURRENT_SOURCE_DIR})
target_compile_definitions(mp3lame PRIVATE HAVE_CONFIG_H)
target_link_libraries(mp3lame PRIVATE m)
target_compile_options(mp3lame PRIVATE -O3)
add_library(smd_mp3 SHARED mp3_encoder_jni.cpp)
target_link_libraries(smd_mp3 PRIVATE mp3lame)
# Android 15 16 KiB-page devices.
target_link_options(mp3lame PRIVATE "-Wl,-z,max-page-size=16384")
target_link_options(smd_mp3 PRIVATE "-Wl,-z,max-page-size=16384")
